spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: sba-registry
server:
  port: 8761

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

#注册中心
eureka:
  client:
    register-with-eureka: false    #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    fetch-registry: false                                        
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  environment: dev

logging:
  level:
    com.netflix.eureka: 'OFF'
    com.netflix.discovery: 'OFF'